import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { ThemeProvider } from "@/hook/ThemeProvider";
import { cn } from "@/lib/utils/shadcn";

import "./globals.css";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="" suppressHydrationWarning>
      <body
        className={cn(
          "bg-muted h-screen min-w-[800px] font-sans antialiased",
          inter.variable,
        )}
      >
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
